# Setup cpack module path (To find NSIS.template.in)
set( CPACK_MODULE_PATH "${CONFIG_PATH}/package" ${CPACK_MODULE_PATH} )

# Common values
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "OFF")
SET(CPACK_BINARY_TZ "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_PACKAGE_RELOCATABLE "true")

# Package information
SET(CPACK_PACKAGE_VENDOR              "${PROJECT_VENDOR}")
SET(CPACK_PACKAGE_NAME                "${PRE_BUILD_PROJECT_NAME}")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PRE_BUILD_PROJECT_DESCRIPTION}")
SET(CPACK_PACKAGE_VERSION             "${PROJECT_VERSION}")
INITVAR(CPACK_PACKAGE_CONTACT         "${PRE_BUILD_PROJECT_CONTACT}" "tvd@lifia.info.unlp.edu.ar")
SET(CPACK_PACKAGE_DESCRIPTION_FILE    "${CONFIG_PATH}/package/COPYING")
SET(CPACK_PACKAGE_FILE_NAME           "${PRE_BUILD_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}")


# Prefix/files/etc
SET(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_CONFIG_INSTALL_PREFIX} )
SET(CPACK_IGNORE_FILES "/include/;/lib/")

# Version
STRING(REPLACE "." ";" VERSION_PARTS "${CPACK_PACKAGE_VERSION}") # Split the version in its components
LIST(GET VERSION_PARTS 0 CPACK_PACKAGE_VERSION_MAJOR)
LIST(GET VERSION_PARTS 1 CPACK_PACKAGE_VERSION_MINOR)
LIST(GET VERSION_PARTS 2 CPACK_PACKAGE_VERSION_PATCH)

# Resources
INITVAR(CPACK_RESOURCE_FILE_LICENSE "${PRE_BUILD_LICENSE_FILE}" "${CONFIG_PATH}/package/COPYING" )
SET(CPACK_RESOURCE_FILE_README  "${CMAKE_ROOT}/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_ROOT}/Templates/CPack.GenericWelcome.txt")

