SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "OFF")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 10")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_SYSTEM_NAME "Windows")
SET(CPACK_TOPLEVEL_TAG "Windows")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "")

# Install property name for registry
SET(CPACK_INSTALL_PROPERTY_NAME "install_path")
