ADD_HEADERS(
	src/functions.h
	src/string.h
	src/singleton.h
	src/buffer.h
	src/any.h
	src/types.h
	src/mcr.h
	src/assert.h
	src/fs.h
	src/url.h
	src/keydefs.h
	src/main.h
	src/tool.h
	src/log.h
	src/settings/settings.h
	src/settings/settingsdelegate.h
	src/pool/pool.h
	src/pool/circularpool.h
	src/task/types.h
	src/task/dispatcher.h
	src/task/dispatcherimpl.h
	src/timer/handler.h
	src/registrator.h
	src/cfg/cfg.h
	src/cfg/propertynode.h
	src/cfg/propertyvalue.h
	src/cfg/treepath.h
	src/cfg/configregistrator.h
	src/cfg/cmd/commandline.h
	src/cfg/cmd/option.h
	src/id/ident.h
	src/id/pool.h
	src/io/dispatcher.h
	src/process/process.h
	src/process/types.h
	src/net/types.h
	src/net/resolver.h
	src/net/socket.h
	src/net/sockaddr.h
	src/net/config.h
	src/net/ipv4/sockaddr.h
	src/net/ipv6/sockaddr.h
	src/netlib/types.h
	src/netlib/manager.h
	src/netlib/requestinfo.h
	src/serializer/serializer.h
	src/serializer/binary.h
	src/serializer/xml.h
	src/xml/types.h
	src/xml/nodehandler.h
	src/xml/documenthandler.h
	src/xml/documentserializer.h
)

ADD_SOURCES(
	src/main.cpp
	src/assert.cpp
	src/assert.h
	src/url.cpp
	src/url.h
	src/keydefs.cpp
	src/keydefs.h
	src/functions.cpp
	src/functions.h
	src/buffer.cpp
	src/buffer.h
	src/fs.cpp
	src/fs.h
	src/md5.c
	src/md5.h
	src/string.cpp
	src/string.h
	src/tool.cpp
	src/tool.h
	src/registrator.cpp
	src/registrator.h
	src/log.cpp
	src/log.h
	src/settings/settings.cpp
	src/settings/settings.h
	src/settings/settingsdelegate.cpp
	src/settings/memory/settings.cpp
	src/settings/memory/settings.h
	src/task/dispatcher.cpp
	src/task/dispatcher.h
	src/task/dispatcherimpl.cpp
	src/task/dispatcherimpl.h
	src/timer/handler.cpp
	src/timer/handler.h
	src/timer/timer.cpp
	src/timer/timer.h
	src/cfg/propertyvalue.cpp
	src/cfg/propertyvalue.h
	src/cfg/propertynode.cpp
	src/cfg/propertynode.h
	src/cfg/treepath.cpp
	src/cfg/treepath.h
	src/cfg/cfg.cpp
	src/cfg/cfg.h
	src/cfg/configregistrator.cpp
	src/cfg/configregistrator.h
	src/cfg/xmlparser.cpp
	src/cfg/xmlparser.h
	src/cfg/cmd/commandline.cpp
	src/cfg/cmd/commandline.h
	src/cfg/cmd/option.cpp
	src/cfg/cmd/option.h
	src/io/dispatcher.cpp
	src/io/dispatcher.h
	src/id/ident.cpp
	src/id/ident.h
	src/id/pool.cpp
	src/id/pool.h
	src/process/process.cpp
	src/process/process.h
	src/net/types.cpp
	src/net/types.h
	src/net/config.cpp
	src/net/resolver.cpp
	src/net/resolver.h
	src/net/socket.cpp
	src/net/socket.h
	src/net/sockaddr.cpp
	src/net/sockaddr.h
	src/net/ipv4/sockaddr.cpp
	src/net/ipv4/sockaddr.h
	src/net/ipv6/sockaddr.cpp
	src/net/ipv6/sockaddr.h
	src/netlib/manager.cpp
	src/netlib/requestinfo.cpp
	src/netlib/request.h
	src/netlib/request.cpp
	src/netlib/reply.h
	src/netlib/reply.cpp
	src/netlib/types.cpp
	src/serializer/xml.cpp
	src/serializer/xml.h
	src/serializer/binary.cpp
	src/serializer/binary.h
	src/xml/types.h
	src/xml/documenthandler.cpp
	src/xml/documenthandler.h
	src/xml/documentserializer.cpp
	src/xml/documentserializer.h
	src/xml/nodehandler.cpp
	src/xml/nodehandler.h
	src/xml/impl/documenthandlerimpl.h
)
