ADD_HEADERS(
	src/presentationenginemanager.h
	src/impl/presentationenginemanager.h
)

ADD_SOURCES(
	src/presentationenginemanager.cpp
	src/FormatterScheduler.cpp
	src/animation/animation.cpp
	src/adapters/ApplicationPlayerAdapter.cpp
	src/adapters/PlayerAdapterManager.cpp
	src/adapters/FormatterPlayerAdapter.cpp
	src/adapters/RuleAdapter.cpp
	src/model/event/eventmanager.cpp
	src/model/event/FormatterEvent.cpp
	src/model/event/transition/EventTransition.cpp
	src/model/event/transition/EndEventTransition.cpp
	src/model/event/transition/BeginEventTransition.cpp
	src/model/event/transition/EventTransitionManager.cpp
	src/model/event/AnchorEvent.cpp
	src/model/event/PresentationEvent.cpp
	src/model/event/SelectionEvent.cpp
	src/model/event/AttributionEvent.cpp
	src/model/presentation/CascadingDescriptor.cpp
	src/model/presentation/FormatterRegion.cpp
	src/model/switches/ExecutionObjectSwitch.cpp
	src/model/switches/SwitchEvent.cpp
	src/model/components/ExecutionObject.cpp
	src/model/components/ApplicationExecutionObject.cpp
	src/model/components/CompositeExecutionObject.cpp
	src/model/components/NodeNesting.cpp
	src/model/link/LinkValueAssessment.cpp
	src/model/link/FormatterLink.cpp
	src/model/link/LinkCompoundTriggerCondition.cpp
	src/model/link/LinkTransitionTriggerCondition.cpp
	src/model/link/LinkAttributeAssessment.cpp
	src/model/link/LinkRepeatAction.cpp
	src/model/link/LinkSimpleAction.cpp
	src/model/link/FormatterCausalLink.cpp
	src/model/link/LinkTriggerCondition.cpp
	src/model/link/LinkAndCompoundTriggerCondition.cpp
	src/model/link/LinkAssessmentStatement.cpp
	src/model/link/LinkAssignmentAction.cpp
	src/model/link/LinkCompoundStatement.cpp
	src/model/link/LinkAction.cpp
	src/model/link/LinkCompoundAction.cpp
	src/FormatterMediator.cpp
	src/emconverter/FormatterConverter.cpp
	src/emconverter/FormatterLinkConverter.cpp
	src/privatebase/PrivateBaseManager.cpp
	src/focus/FormatterFocusManager.cpp
	src/impl/editingcommandevents.cpp
	src/impl/presentationenginemanager.cpp
	src/impl/formattermediator.cpp
	include/FormatterScheduler.h
	src/animation/animation.h
	include/adapters/ApplicationPlayerAdapter.h
	include/adapters/PlayerAdapterManager.h
	include/adapters/FormatterPlayerAdapter.h
	include/adapters/INclEditListener.h
	include/adapters/RuleAdapter.h
	src/model/event/eventmanager.h
	include/model/FormatterEvent.h
	include/model/EventTransition.h
	include/model/EndEventTransition.h
	include/model/BeginEventTransition.h
	include/model/EventTransitionManager.h
	include/model/AnchorEvent.h
	include/model/PresentationEvent.h
	include/model/SelectionEvent.h
	include/model/AttributionEvent.h
	include/model/IAttributeValueMaintainer.h
	include/model/CascadingDescriptor.h
	include/model/FormatterRegion.h
	include/model/ExecutionObjectSwitch.h
	include/model/SwitchEvent.h
	include/model/ExecutionObject.h
	include/model/ApplicationExecutionObject.h
	include/model/CompositeExecutionObject.h
	include/model/LinkListener.h
	include/model/IEventListener.h
	include/model/NodeNesting.h
	include/model/LinkValueAssessment.h
	include/model/LinkAssessment.h
	include/model/FormatterLink.h
	include/model/LinkCompoundTriggerCondition.h
	include/model/LinkTransitionTriggerCondition.h
	include/model/LinkAttributeAssessment.h
	include/model/LinkRepeatAction.h
	include/model/LinkSimpleAction.h
	include/model/FormatterCausalLink.h
	include/model/LinkCondition.h
	include/model/LinkTriggerCondition.h
	include/model/LinkTriggerListener.h
	include/model/LinkStatement.h
	include/model/LinkAndCompoundTriggerCondition.h
	include/model/LinkAssessmentStatement.h
	include/model/LinkAssignmentAction.h
	include/model/LinkCompoundStatement.h
	include/model/LinkAction.h
	include/model/LinkActionProgressionListener.h
	include/model/LinkCompoundAction.h
	include/model/LinkActionListener.h
	include/FormatterMediator.h
	include/emconverter/FormatterConverter.h
	include/emconverter/FormatterLinkConverter.h
	include/privatebase/IPrivateBaseManager.h
	include/privatebase/PrivateBaseManager.h
	include/focus/FormatterFocusManager.h
	src/impl/editingcommandevents.h
	src/impl/formattermediator.h
)
