<?xml version="1.0" encoding="ISO-8859-1"?>
<ncl id="test_region_width_1" xmlns="http://www.ncl.org.br/NCL3.0/EDTVProfile">
	<head>
		<regionBase device="systemScreen(1)">
			<region id="reg"/>
		</regionBase>
		<descriptorBase>
			<descriptor id="desc" region="reg" />
		</descriptorBase>
	</head>
	<body>
		<port id="port1" component="image1" />
		<media id="image1" src="../../../../images/blue.jpg" >
		</media>
	</body>
</ncl>
