# - Try to find GStreamer
# Once done this will define
#
#  GSTREAMER_0_10_FOUND - system has GStreamer
#  GSTREAMER_0_10_INCLUDE_DIR - the GStreamer include directory
#  GSTREAMER_0_10_LIBRARIES - the libraries needed to use GStreamer
#  GSTREAMER_0_10_DEFINITIONS - Compiler switches required for using GStreamer

# Copyright (c) 2006, Tim Beaulen <tbscope@gmail.com>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

FIND_PATH(GSTREAMER_0_10_INCLUDE_DIR gst/gst.h
   PATHS
   /usr/include
   /usr/local/include
   /usr/include/gstreamer-0.10
   )

FIND_LIBRARY(GSTREAMER_0_10_LIBRARIES
   NAMES gstreamer-0.10
   PATHS /usr/lib /usr/local/lib
   )

FIND_LIBRARY(GSTREAMER_0_10_BASE_LIBRARY
   NAMES gstbase-0.10
   PATHS /usr/lib /usr/local/lib
   )
   
FIND_LIBRARY(GSTREAMER_0_10_PBUTILS_LIBRARY
  NAMES gstpbutils-0.10
  PATHS /usr/lib /usr/local/lib
  )

FIND_LIBRARY(GSTREAMER_0_10_VIDEO_LIBRARY
  NAMES gstvideo-0.10
  PATHS /usr/lib /usr/local/lib
  )
   
FIND_LIBRARY(GSTREAMER_0_10_AUDIO_LIBRARY
  NAMES gstaudio-0.10
  PATHS /usr/lib /usr/local/lib
  )

FIND_LIBRARY(GSTREAMER_0_10_APP_LIBRARY
  NAMES gstapp-0.10
  PATHS /usr/lib /usr/local/lib
  )

# find requited glib
IF( NOT GLIB_FOUND )
	FIND_PACKAGE( Glib REQUIRED )
	IF ( GLIB_FOUND )
		SET ( GSTREAMER_0_10_INCLUDE_DIR ${GSTREAMER_0_10_INCLUDE_DIR} ${GLIB_INCLUDE_DIRS} )
		SET ( GSTREAMER_0_10_LIBRARIES ${GSTREAMER_0_10_LIBRARIES} ${GLIB_LIBRARIES} )
	ENDIF ( GLIB_FOUND )
ENDIF( NOT GLIB_FOUND )

INCLUDE(FindPackageHandleStandardArgs)
SET(GSTREAMER_0_10_INCLUDE_DIR ${GSTREAMER_0_10_INCLUDE_DIR} ${LIBXML2_INCLUDE_DIR})
SET(GSTREAMER_0_10_LIBRARIES ${GSTREAMER_0_10_LIBRARIES} ${GSTREAMER_0_10_BASE_LIBRARY} ${GSTREAMER_0_10_VIDEO_LIBRARY} ${GSTREAMER_0_10_PBUTILS_LIBRARY} ${GSTREAMER_0_10_AUDIO_LIBRARY} ${GSTREAMER_0_10_APP_LIBRARY} )
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GStreamer_0_10  DEFAULT_MSG  GSTREAMER_0_10_LIBRARIES GSTREAMER_0_10_INCLUDE_DIR GSTREAMER_0_10_BASE_LIBRARY GSTREAMER_0_10_VIDEO_LIBRARY GSTREAMER_0_10_PBUTILS_LIBRARY GSTREAMER_0_10_AUDIO_LIBRARY)
MARK_AS_ADVANCED(GSTREAMER_0_10_INCLUDE_DIR GSTREAMER_0_10_LIBRARIES GSTREAMER_0_10_BASE_LIBRARY GSTREAMER_0_10_VIDEO_LIBRARY GSTREAMER_0_10_PBUTILS_LIBRARY GSTREAMER_0_10_AUDIO_LIBRARY)
