enyo.depends(
	"restore.js",
	"internet.js",
	"system.js",
	"about_system.js",
	"parental.js",
	"development.js",
	"update_channels.js",
	"ginga.js",
	"tda.js",
	"wizard.js",
	"servicesInfo.js",
	"services.js"
);
