Find_Package( FFMPEG REQUIRED avformat avcodec avfilter avutil )
set(FFMPEG-AVUTIL_CFLAGS "-D__STDC_CONSTANT_MACROS")
LIST(APPEND FFMPEG-AVFORMAT_LIBRARIES "swscale")
ADD_DEPENDENTS( FFMPEG-AVFORMAT FFMPEG-AVCODEC FFMPEG-AVFILTER FFMPEG-AVUTIL )
