Find_Package( SDL  )
Find_Package( SDL_image  )
Find_Package( SDL_ttf  )
find_package( PNG  )

SET(SDL_LIBRARIES      ${SDL_LIBRARY})
SET(SDLIMAGE_LIBRARIES ${SDLIMAGE_LIBRARY})
SET(SDLTTF_LIBRARIES   ${SDLTTF_LIBRARY})

ADD_DEPENDENTS( PNG SDL SDLIMAGE SDLTTF )
