ADD_SOURCES(
	src/impl/win32/system.h
	src/impl/win32/system.cpp
	src/impl/win32/window.h
	src/impl/win32/window.cpp
	src/impl/win32/videooverlay.h
	src/impl/win32/videooverlay.cpp
	src/impl/win32/dispatcher.h
	src/impl/win32/dispatcher.cpp
	src/impl/win32/keys.cpp
)
