ADD_HEADERS(
	src/factory.h
	src/audio.h
	src/audio/audioplayer.h
	src/canvas.h
	src/color.h
	src/fontinfo.h
	src/fontmanager.h
	src/input.h
	src/inputmanager.h
	src/streaminfo.h
	src/mediaplayer.h
	src/player.h
	src/point.h
	src/rect.h
	src/screen.h
	src/size.h
	src/surface.h
	src/system.h
	src/types.h
	src/webviewer.h
	src/window.h
	src/settings/audio.h
	src/settings/layer.h
	src/settings/screen.h
	src/layer/layer.h
	src/layer/layermanager.h
	src/layer/surface.h
)

ADD_SOURCES(
	src/factory.cpp
	src/audio.cpp
	src/audio/audioplayer.cpp
	src/canvas.cpp
	src/color.cpp
	src/event.h
	src/fontinfo.cpp
	src/fontmanager.cpp
	src/input.cpp
	src/inputmanager.cpp
	src/streaminfo.h
	src/streaminfo.cpp
	src/mediaplayer.cpp
	src/mediaplayerimpl.h
	src/mediaplayerimpl.cpp
	src/singlemediaplayer.h
	src/singlemediaplayer.cpp
	src/player.cpp
	src/point.cpp
	src/rect.cpp
	src/screen.cpp
	src/size.cpp
	src/surface.cpp
	src/system.cpp
	src/types.cpp
	src/text/font.h
	src/text/font.cpp
	src/text/glyphrun.h
	src/videooverlay.h
	src/videooverlay.cpp
	src/webviewer.cpp
	src/window.cpp
	src/settings/audio.cpp
	src/settings/layer.cpp
	src/settings/screen.cpp
	src/layer/layer.cpp
	src/layer/layermanager.cpp
	src/layer/surface.cpp
	src/impl/dummy/window.h
	src/impl/dummy/window.cpp
	src/impl/dummy/canvas.h
	src/impl/dummy/canvas.cpp
	src/impl/dummy/surface.h
	src/impl/dummy/surface.cpp
	src/impl/dummy/player.h
	src/impl/dummy/player.cpp
	src/impl/dummy/mediaplayer.h
	src/impl/dummy/mediaplayer.cpp
	src/impl/dummy/dummywebviewer.h
	src/impl/dummy/dummywebviewer.cpp
	src/impl/dummy/fontmanager.h
	src/impl/dummy/fontmanager.cpp
	src/impl/dummy/font.h
	src/impl/dummy/font.cpp
	src/impl/dummy/glyphrun.h
	src/impl/dummy/glyphrun.cpp
	src/impl/dummy/audio.h
	src/impl/dummy/audio.cpp
)
