ADD_SOURCES(
	src/impl/ppapi/system.h
	src/impl/ppapi/system.cpp
	src/impl/ppapi/window.h
	src/impl/ppapi/window.cpp
	src/impl/ppapi/ppapi.h
	src/impl/ppapi/ppapi.cpp
	src/impl/ppapi/key.h
	src/impl/ppapi/key.cpp
)
