ADD_SOURCES(
  src/testplatform.cpp
  src/test.cpp
  src/testlog.cpp
  src/step.cpp
  src/volume.cpp
  src/mute.cpp
  src/mediaplayerstep.cpp
  src/util.cpp
  src/input/map.cpp
  src/mixer/volume.cpp
  src/mixer/mute.cpp
  src/mixer/output.cpp
  src/display/modes.cpp
  src/display/aspect.cpp
  src/canvas/canvas.cpp
  src/canvas/composition.cpp
  src/canvas/format.cpp
  src/mediaplayer/mediaend.cpp
  src/mediaplayer/volume.cpp
  src/mediaplayer/format.cpp
  src/mediaplayer/resize.cpp
  src/mediaplayer/mute.cpp
  src/dvb/scan.cpp
  src/dvb/video.cpp
  src/dvb/download.cpp
  src/dvb/signal.cpp
  src/types.h
  src/testplatform.h
  src/test.h
  src/testlog.h
  src/step.h
  src/volume.h
  src/mute.h
  src/mediaplayerstep.h
  src/util.h
  src/input/map.h
  src/mixer/volume.h
  src/mixer/mute.h
  src/mixer/output.h
  src/display/modes.h
  src/display/aspect.h
  src/canvas/canvas.h
  src/canvas/composition.h
  src/canvas/format.h
  src/mediaplayer/mediaend.h
  src/mediaplayer/volume.h
  src/mediaplayer/format.h
  src/mediaplayer/resize.h
  src/mediaplayer/mute.h
  src/dvb/scan.h
  src/dvb/video.h
  src/dvb/download.h
  src/dvb/signal.h
)

