CONFIGURE_FILE( ${PROJECT_SOURCE_DIR}/${PRE_BUILD_PROJECT_NAME}.desktop.cin
	${PROJECT_BINARY_DIR}/${PRE_BUILD_PROJECT_NAME}.desktop
)

INSTALL( PROGRAMS ${PROJECT_BINARY_DIR}/${PRE_BUILD_PROJECT_NAME}.desktop
	DESTINATION share/applications
)
