ADD_SOURCES(
	test/src/main.cpp
	test/src/util.cpp
	test/src/input.cpp
	test/src/system.cpp
	test/src/window.cpp
	test/src/canvas/image.cpp
	test/src/canvas/canvas_flush.cpp
	test/src/canvas/canvas_invalidateRegion.cpp
	test/src/canvas/canvas_draw.cpp
	test/src/canvas/surface.cpp
	test/src/canvas/surface_benchmark.cpp
	test/src/canvas/surface_location.cpp
	test/src/canvas/surface_zindex.cpp
	test/src/canvas/surface_visible.cpp
	test/src/canvas/surface_setColor.cpp
	test/src/canvas/surface_opacity.cpp
	test/src/canvas/surface_clear.cpp
	test/src/canvas/surface_clip.cpp
	test/src/canvas/surface_compositionMode.cpp
	test/src/canvas/surface_compositionMode_transparency.cpp
	test/src/canvas/surface_compositionMode_opacity.cpp
	test/src/canvas/surface_compound.cpp
	test/src/canvas/surface_drawLine.cpp
	test/src/canvas/surface_drawRoundRect.cpp
	test/src/canvas/surface_constructor.cpp
	test/src/canvas/surface_drawRect.cpp
	test/src/canvas/surface_drawPolygon.cpp
	test/src/canvas/surface_drawText.cpp
	test/src/canvas/surface_drawTextWithBox.cpp
	test/src/canvas/surface_drawEllipse.cpp
	test/src/canvas/surface_pixelColor.cpp
	test/src/canvas/surface_fillRoundRect.cpp
	test/src/canvas/surface_fillRect.cpp
	test/src/canvas/surface_fillPolygon.cpp
	test/src/canvas/surface_fillEllipse.cpp
	test/src/canvas/surface_measureText.cpp
	test/src/canvas/surface_markDirty.cpp
	test/src/canvas/surface_blit.cpp
	test/src/canvas/surface_resize.cpp
	test/src/canvas/surface_scale.cpp
	test/src/canvas/surface_rotate.cpp
	test/src/canvas/surface_pointInBounds.cpp
	test/src/canvas/surface_font.cpp
	test/src/canvas/surface_invalidateRegion.cpp
	test/src/canvas/surface_fontAscent.cpp
	test/src/canvas/surface_fontDescent.cpp
)
