ADD_HEADERS(
	src/types.h
	src/player.h
	src/property/property.h
	src/property/types.h
	src/player/settings.h
	src/player/keys.h
	src/player/lua/event/types.h
	src/device.h
	src/system.h
	src/remote/device.h
)

ADD_SOURCES(
	src/types.cpp
	src/device.cpp
	src/system.cpp
	src/player.cpp
	src/player/timelinetimer.cpp
	src/player/graphicplayer.cpp
	src/player/surfaceproperties.cpp
	src/player/soundproperties.cpp
	src/player/graphicproperties.cpp
	src/player/focusproperties.cpp
	src/player/imageplayer.cpp
	src/player/animeplayer.cpp
	src/player/textplayer.cpp
	src/player/settings.cpp
	src/player/keys.cpp
	src/player/soundplayer.cpp
	src/player/videoplayer.cpp
	src/player/htmlplayer.cpp
	src/player/luaplayer.cpp
	src/player/lua/lua.cpp
	src/player/lua/event/types.cpp
	src/player/lua/event/event.cpp
	src/player/lua/event/class/key.cpp
	src/player/lua/event/class/pointer.cpp
	src/player/lua/event/class/ncl.cpp
	src/player/lua/event/class/user.cpp
	src/player/lua/event/class/tcp.cpp
	src/player/lua/event/class/si.cpp
	src/player/lua/canvas/canvas.cpp
	src/player/lua/canvas/surfacewrapper.cpp
	src/player/lua/settings/settings.cpp
	src/player/lua/persistent/persistent.cpp
	src/player/lua/persistent/dbdata.cpp
	src/player/lua/persistent/types.cpp
	src/property/types.cpp
	src/property/check.h
	src/property/forwardproperty.h
	src/property/propertyimpl.h
	src/property/property.cpp
	src/property/compositeproperty.cpp
	src/remote/device.cpp
	src/remote/mediaplayer.cpp
	src/player/timelinetimer.h
	src/player/graphicplayer.h
	src/player/surfaceproperties.h
	src/player/soundproperties.h
	src/player/graphicproperties.h
	src/player/focusproperties.h
	src/player/imageplayer.h
	src/player/animeplayer.h
	src/player/textplayer.h
	src/player/soundplayer.h
	src/player/videoplayer.h
	src/player/htmlplayer.h
	src/player/luaplayer.h
	src/player/lua/lua.h
	src/player/lua/event/event.h
	src/player/lua/event/class/key.h
	src/player/lua/event/class/pointer.h
	src/player/lua/event/class/ncl.h
	src/player/lua/event/class/user.h
	src/player/lua/event/class/tcp.h
	src/player/lua/canvas/canvas.h
	src/player/lua/canvas/surfacewrapper.h
	src/player/lua/settings/settings.h
	src/player/lua/persistent/persistent.h
	src/player/lua/persistent/dbdata.h
	src/player/lua/persistent/types.h
	src/property/compositeproperty.h
	src/remote/mediaplayer.h
)
