ADD_SOURCES(
  src/lzapper.h
  src/lzapper.cpp
  src/view/alignment.h
  src/view/alignment.cpp
  src/view/color.h
  src/view/color.cpp
  src/view/luacallback.h
  src/view/luacallback.cpp
  src/view/view.h
  src/view/view.cpp
  src/view/datetime.h
  src/view/datetime.cpp
  src/view/widget/bar.h
  src/view/widget/bar.cpp
  src/view/widget/borderedwindow.h
  src/view/widget/borderedwindow.cpp
  src/view/widget/button.h
  src/view/widget/button.cpp
  src/view/widget/buttonset.h
  src/view/widget/buttonset.cpp
  src/view/widget/buttongrid.h
  src/view/widget/buttongrid.cpp
  src/view/widget/extendedbuttonset.h
  src/view/widget/extendedbuttonset.cpp
  src/view/widget/combobox.h
  src/view/widget/combobox.cpp
  src/view/widget/dialog.h
  src/view/widget/dialog.cpp
  src/view/widget/image.h
  src/view/widget/image.cpp
  src/view/widget/label.h
  src/view/widget/label.cpp
  src/view/widget/list.h
  src/view/widget/list.cpp
  src/view/widget/maskedlabel.h
  src/view/widget/maskedlabel.cpp
  src/view/widget/nav.h
  src/view/widget/nav.cpp
  src/view/widget/progressbar.h
  src/view/widget/progressbar.cpp
  src/view/widget/pindialog.h
  src/view/widget/pindialog.cpp
  src/view/widget/slidebar.h
  src/view/widget/slidebar.cpp
  src/view/widget/textarea.h
  src/view/widget/textarea.cpp
  src/view/widget/verticalset.h
  src/view/widget/verticalset.cpp
  src/view/widget/widget.h
  src/view/widget/widget.cpp
  src/view/widget/widgetset.h
  src/view/widget/widgetset.cpp
  src/view/widget/window.h
  src/view/widget/window.cpp
  src/view/widget/scrollbar.h
  src/view/widget/scrollbar.cpp
  src/view/widget/scrollarrow.h
  src/view/widget/scrollarrow.cpp
  src/view/widget/imageviewer.h
  src/view/widget/imageviewer.cpp
  src/view/widget/videoviewer.h
  src/view/widget/videoviewer.cpp
  src/view/widget/frame.h
  src/view/widget/frame.cpp
  src/view/widget/timeslots.h
  src/view/widget/timeslots.cpp
  src/view/widget/schedule.h
  src/view/widget/schedule.cpp
  src/view/widget/schedulerow.h
  src/view/widget/schedulerow.cpp
  src/view/modules/wgt.h
  src/view/modules/wgt.cpp
  src/view/modules/canvas.h
  src/view/modules/canvas.cpp
  src/view/modules/fs.h
  src/view/modules/fs.cpp
  src/view/modules/application_helper.h
  src/view/modules/application_helper.cpp
  src/view/modules/label.cpp
  src/view/modules/list.cpp
  src/view/modules/luawgt.h
  src/view/modules/window.cpp
  src/view/modules/button.cpp
  src/view/modules/bar.cpp
  src/view/modules/progressbar.cpp
  src/view/modules/combobox.cpp
  src/view/modules/image.cpp
  src/view/modules/imageviewer.cpp
  src/view/modules/videoviewer.cpp
  src/view/modules/slidebar.cpp
  src/view/modules/textarea.cpp
  src/view/modules/verticalset.cpp
  src/view/modules/dialogs.cpp
  src/view/modules/schedule.cpp
  src/view/modules/scroll.cpp
)

