<?xml version="1.0" encoding="ISO-8859-1"?>
<ncl id="key_navigation" xmlns="http://www.ncl.org.br/NCL3.0/EDTVProfile">
	<head>
		<regionBase>
			<region id="reg_0_0" width="25%" height="25%" left="0%" top="0%" />
			<region id="reg_0_1" width="25%" height="25%" left="25%" top="0%" />
			<region id="reg_0_2" width="25%" height="25%" left="50%" top="0%" />
			<region id="reg_0_3" width="25%" height="25%" left="75%" top="0%" />
			<region id="reg_1_0" width="25%" height="25%" left="0%" top="25%" />
			<region id="reg_1_1" width="25%" height="25%" left="25%" top="25%" />
			<region id="reg_1_2" width="25%" height="25%" left="50%" top="25%" />
			<region id="reg_1_3" width="25%" height="25%" left="75%" top="25%" />
			<region id="reg_2_0" width="25%" height="25%" left="0%" top="50%" />
			<region id="reg_2_1" width="25%" height="25%" left="25%" top="50%" />
			<region id="reg_2_2" width="25%" height="25%" left="50%" top="50%" />
			<region id="reg_2_3" width="25%" height="25%" left="75%" top="50%" />
			<region id="reg_3_0" width="25%" height="25%" left="0%" top="75%" />
			<region id="reg_3_1" width="25%" height="25%" left="25%" top="75%" />
			<region id="reg_3_2" width="25%" height="25%" left="50%" top="75%" />
			<region id="reg_3_3" width="25%" height="25%" left="75%" top="75%" />
		</regionBase>
		<descriptorBase>
			<descriptor id="desc_0_0" region="reg_0_0" focusIndex="f_0_0" focusBorderColor="white" selBorderColor="teal" focusBorderWidth="3"  moveDown="f_1_0" moveRight="f_0_1" />
			<descriptor id="desc_0_1" region="reg_0_1" focusIndex="f_0_1" focusBorderColor="black" selBorderColor="aqua" focusBorderWidth="4"  moveDown="f_1_1" moveLeft="f_0_0" moveRight="f_0_2" />
			<descriptor id="desc_0_2" region="reg_0_2" focusIndex="f_0_2" focusBorderColor="silver" selBorderColor="navy" focusBorderWidth="5"  moveDown="f_1_2" moveLeft="f_0_1" moveRight="f_0_3" />
			<descriptor id="desc_0_3" region="reg_0_3" focusIndex="f_0_3" focusBorderColor="gray" selBorderColor="blue" focusBorderWidth="6"  moveDown="f_1_3" moveLeft="f_0_2" />
			<descriptor id="desc_1_0" region="reg_1_0" focusIndex="f_1_0" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="red" selBorderColor="olive" focusBorderWidth="7"  moveUp="f_0_0" moveDown="f_2_0" moveRight="f_1_1" />
			<descriptor id="desc_1_1" region="reg_1_1" focusIndex="f_1_1" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="maroon" selBorderColor="yellow" focusBorderWidth="8"  moveUp="f_0_1" moveDown="f_2_1" moveLeft="f_1_0" moveRight="f_1_2" />
			<descriptor id="desc_1_2" region="reg_1_2" focusIndex="f_1_2" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="fuchsia" selBorderColor="green" focusBorderWidth="9"  moveUp="f_0_2" moveDown="f_2_2" moveLeft="f_1_1" moveRight="f_1_3" />
			<descriptor id="desc_1_3" region="reg_1_3" focusIndex="f_1_3" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="purple" selBorderColor="lime" focusBorderWidth="10"  moveUp="f_0_3" moveDown="f_2_3" moveLeft="f_1_2" />
			<descriptor id="desc_2_0" region="reg_2_0" focusIndex="f_2_0" focusBorderColor="lime" selBorderColor="purple" focusBorderWidth="11"  moveUp="f_1_0" moveDown="f_3_0" moveRight="f_2_1" />
			<descriptor id="desc_2_1" region="reg_2_1" focusIndex="f_2_1" focusBorderColor="green" selBorderColor="fuchsia" focusBorderWidth="12"  moveUp="f_1_1" moveDown="f_3_1" moveLeft="f_2_0" moveRight="f_2_2" />
			<descriptor id="desc_2_2" region="reg_2_2" focusIndex="f_2_2" focusBorderColor="yellow" selBorderColor="maroon" focusBorderWidth="13"  moveUp="f_1_2" moveDown="f_3_2" moveLeft="f_2_1" moveRight="f_2_3" />
			<descriptor id="desc_2_3" region="reg_2_3" focusIndex="f_2_3" focusBorderColor="olive" selBorderColor="red" focusBorderWidth="14"  moveUp="f_1_3" moveDown="f_3_3" moveLeft="f_2_2" />
			<descriptor id="desc_3_0" region="reg_3_0" focusIndex="f_3_0" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="blue" selBorderColor="gray" focusBorderWidth="15"  moveUp="f_2_0" moveRight="f_3_1" />
			<descriptor id="desc_3_1" region="reg_3_1" focusIndex="f_3_1" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="navy" selBorderColor="silver" focusBorderWidth="16"  moveUp="f_2_1" moveLeft="f_3_0" moveRight="f_3_2" />
			<descriptor id="desc_3_2" region="reg_3_2" focusIndex="f_3_2" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="aqua" selBorderColor="black" focusBorderWidth="17"  moveUp="f_2_2" moveLeft="f_3_1" moveRight="f_3_3" />
			<descriptor id="desc_3_3" region="reg_3_3" focusIndex="f_3_3" focusSrc="../resources/images/focus.png" focusSelSrc="../resources/images/sel.png" focusBorderColor="teal" selBorderColor="white" focusBorderWidth="18"  moveUp="f_2_3" moveLeft="f_3_2" />
		</descriptorBase>
	</head>
	<body>
		<port id="entry_0_0" component="media_0_0" />
		<media id="media_0_0" src="../resources/images/image.png" descriptor="desc_0_0" />
		<port id="entry_0_1" component="media_0_1" />
		<media id="media_0_1" src="../resources/images/image.png" descriptor="desc_0_1" />
		<port id="entry_0_2" component="media_0_2" />
		<media id="media_0_2" src="../resources/images/image.png" descriptor="desc_0_2" />
		<port id="entry_0_3" component="media_0_3" />
		<media id="media_0_3" src="../resources/images/image.png" descriptor="desc_0_3" />
		<port id="entry_1_0" component="media_1_0" />
		<media id="media_1_0" src="../resources/text/navigation_test.txt" descriptor="desc_1_0" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_1_1" component="media_1_1" />
		<media id="media_1_1" src="../resources/text/navigation_test.txt" descriptor="desc_1_1" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_1_2" component="media_1_2" />
		<media id="media_1_2" src="../resources/text/navigation_test.txt" descriptor="desc_1_2" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_1_3" component="media_1_3" />
		<media id="media_1_3" src="../resources/text/navigation_test.txt" descriptor="desc_1_3" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_2_0" component="media_2_0" />
		<media id="media_2_0" src="../resources/images/image.png" descriptor="desc_2_0" />
		<port id="entry_2_1" component="media_2_1" />
		<media id="media_2_1" src="../resources/images/image.png" descriptor="desc_2_1" />
		<port id="entry_2_2" component="media_2_2" />
		<media id="media_2_2" src="../resources/images/image.png" descriptor="desc_2_2" />
		<port id="entry_2_3" component="media_2_3" />
		<media id="media_2_3" src="../resources/images/image.png" descriptor="desc_2_3" />
		<port id="entry_3_0" component="media_3_0" />
		<media id="media_3_0" src="../resources/text/navigation_test.txt" descriptor="desc_3_0" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_3_1" component="media_3_1" />
		<media id="media_3_1" src="../resources/text/navigation_test.txt" descriptor="desc_3_1" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_3_2" component="media_3_2" />
		<media id="media_3_2" src="../resources/text/navigation_test.txt" descriptor="desc_3_2" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
		<port id="entry_3_3" component="media_3_3" />
		<media id="media_3_3" src="../resources/text/navigation_test.txt" descriptor="desc_3_3" >
            <property name="fontSize" value="32" />
            <property name="fontColor" value="black" />
        </media>
	</body>
</ncl>
