DEF_OPTIONS(ZAPPER_MOUNT mdev)
DEF_OPTIONS(ZAPPER_IMPL CS ST AML PC ANDROID DEFAULT PC ON)
DEF_OPTIONS(ZAPPER_LOGOS TS NETWORK)

# Libraries
ADD_INTERNAL_COMPONENTS( pvr mpegparser connector canvas util )
ADD_BOOST_COMPONENTS( system filesystem thread )

find_package( ZLIB REQUIRED )
ADD_DEPENDENTS( ZLIB )
