DEF_OPTIONS(DVB DVB BDA DEFAULT DVB ON)
DEF_OPTIONS(RTP RTP )
DEF_OPTIONS(CSA DVBCSA)

ADD_INTERNAL_COMPONENTS( connector util )

ADD_BOOST_COMPONENTS( system filesystem thread )

find_package( ZLIB REQUIRED )
ADD_DEPENDENTS( ZLIB )

