ADD_HEADERS(
	src/resourcemanager.h
	src/time.h
	src/tuner/types.h
	src/tuner/tuner.h
	src/tuner/scanextension.h
	src/service/service.h
	src/service/serviceid.h
	src/service/extension/extension.h
	src/service/extension/time/timeextension.h
	src/service/extension/ewbs/extension.h
	src/service/extension/epg/epgextension.h
	src/service/extension/download/downloaderextension.h
	src/service/extension/download/downloadinfo.h
	src/service/extension/application/controller/controller.h
	src/service/extension/application/controller/playeradapter.h
	src/service/extension/application/controller/runtask.h
	src/service/extension/application/controller/spawner.h
	src/service/extension/application/factory.h
	src/service/extension/application/applicationid.h
	src/service/extension/application/application.h
	src/service/extension/application/extension.h
	src/service/extension/application/types.h
	src/service/extension/application/factories/profile/ginga-ncl/nclapplication.h
	src/service/extension/application/factories/profile/ginga-ncl/nclprofile.h
	src/service/extension/application/factories/profile/hbbtv/hbbtvprofile.h
	src/service/extension/application/factories/aitfactory.h
	src/service/extension/application/factories/profile.h
	src/service/extension/player/types.h
	src/service/extension/player/extension.h
	src/service/extension/player/streaminfo.h
	src/service/extension/player/delegate.h
	src/service/extension/player/tsdelegate.h
	src/service/extension/player/player.h
	src/service/extension/player/esplayer.h
	src/service/extension/player/caption/viewer.h
	src/service/extension/player/caption/delegate.h
	src/service/servicemanager.h
	src/service/types.h
	src/service/serviceprovider.h
	src/muxer/ts/muxer.h
	src/muxer/ts/out/output.h
	src/muxer/ts/out/rtp.h
	src/muxer/ts/out/file.h
	src/demuxer/types.h
	src/demuxer/ts/types.h
	src/demuxer/ts/demuxer.h
	src/demuxer/ts/demuxerimpl.h
	src/demuxer/ts/filter.h
	src/demuxer/descriptors.h
	src/demuxer/descriptors/generic.h
	src/demuxer/descriptors/demuxers.h
	src/demuxer/descriptors/ca.h
	src/demuxer/descriptors/lcn.h
	src/demuxer/descriptors/parental.h
	src/demuxer/ts.h
	src/demuxer/text.h
	src/demuxer/psi/psi.h
	src/demuxer/psi/psidemuxer.h
	src/demuxer/psi/tableinfo.h
	src/demuxer/psi/psifilter.h
	src/demuxer/psi/pat.h
	src/demuxer/psi/patdemuxer.h
	src/demuxer/psi/cat.h
	src/demuxer/psi/catdemuxer.h
	src/demuxer/psi/pmt.h
	src/demuxer/psi/pmtdemuxer.h
	src/demuxer/psi/eitdemuxer.h
	src/demuxer/psi/eit.h
	src/demuxer/psi/cdt.h
	src/demuxer/psi/cdtdemuxer.h
	src/demuxer/psi/download/sdttdemuxer.h
	src/demuxer/psi/download/sdtt.h
	src/demuxer/psi/nit.h
	src/demuxer/psi/sdtdemuxer.h
	src/demuxer/psi/totdemuxer.h
	src/demuxer/psi/tot.h
	src/demuxer/psi/mjd.h
	src/demuxer/psi/sdt.h
	src/demuxer/psi/raw.h
	src/demuxer/psi/rawdemuxer.h
	src/demuxer/psi/ecmdemuxer.h
	src/demuxer/psi/dsmcc/dsmcc.h
	src/demuxer/psi/dsmcc/event.h
	src/demuxer/psi/dsmcc/module.h
	src/demuxer/psi/dsmcc/dsmccfilter.h
	src/demuxer/psi/dsmcc/objectcarouselfilter.h
	src/demuxer/psi/dsmcc/downloadfilter.h
	src/demuxer/psi/dsmcc/module/moduledata.h
	src/demuxer/psi/dsmcc/module/filedata.h
	src/demuxer/psi/dsmcc/module/memorydata.h
	src/demuxer/psi/dsmcc/module/resourcepool.h
	src/demuxer/psi/dsmcc/parser.h
	src/demuxer/psi/dsmcc/dsi.h
	src/demuxer/psi/dsmcc/streameventdemuxer.h
	src/demuxer/psi/dsmcc/datacarouselhelper.h
	src/demuxer/psi/dsmcc/dii.h
	src/demuxer/psi/dsmcc/dsmccdemuxer.h
	src/demuxer/psi/dsmcc/biop/ior.h
	src/demuxer/psi/dsmcc/biop/object.h
	src/demuxer/psi/dsmcc/biop/directory.h
	src/demuxer/psi/dsmcc/biop/file.h
	src/demuxer/psi/dsmcc/biop/biop.h
	src/demuxer/psi/dsmcc/biop/objectlocation.h
	src/demuxer/psi/dsmcc/biop/streamevent.h
	src/demuxer/psi/application/aitdemuxer.h
	src/demuxer/psi/application/ait.h
	src/demuxer/psi/application/types.h
	src/demuxer/psi/nitdemuxer.h
	src/demuxer/pes/types.h
	src/demuxer/pes/pesdemuxer.h
	src/demuxer/pes/caption/caption.h
	src/demuxer/pes/caption/captiondemuxer.h
	src/demuxer/pes/caption/captiondata.h
	src/provider/ts/provider.h
	src/provider/ts/filter.h
	src/provider/ts/data/filefrontend.h
	src/provider/ts/data/frontend.h
	src/provider/ts/data/networkfrontend.h
	src/provider/filter.h
	src/provider/frontend.h
	src/provider/broadcast/frontend.h
	src/provider/broadcast/config.h
	src/provider/broadcast/isdbtconfig.h
	src/provider/broadcast/satelliteconfig.h
	src/provider/provider.h
	src/stream/pipe.h
	src/stream/basicpipe.h
	src/stream/dummy/pipe.h
	src/types.h
	src/language.h
)

ADD_SOURCES(
	src/language.cpp
	src/resourcemanager.cpp
	src/time.cpp
	src/tuner/tuner.cpp
	src/tuner/scanextension.cpp
	src/service/extension/extension.cpp
	src/service/extension/time/timeextension.cpp
	src/service/extension/ewbs/extension.cpp
	src/service/extension/epg/epgextension.cpp
	src/service/extension/download/downloadinfo.cpp
	src/service/extension/download/downloaderextension.cpp
	src/service/extension/application/controller/controller.cpp
	src/service/extension/application/controller/playeradapter.cpp
	src/service/extension/application/controller/runtask.cpp
	src/service/extension/application/controller/spawner.cpp
	src/service/extension/application/applicationid.cpp
	src/service/extension/application/factory.cpp
	src/service/extension/application/application.cpp
	src/service/extension/application/extension.cpp
	src/service/extension/application/factories/aitfactory.cpp
	src/service/extension/application/factories/profile/ginga-ncl/nclprofile.cpp
	src/service/extension/application/factories/profile/ginga-ncl/nclapplication.cpp
	src/service/extension/application/factories/profile/hbbtv/hbbtvprofile.cpp
	src/service/extension/application/factories/profile.cpp
	src/service/extension/player/extension.cpp
	src/service/extension/player/streaminfo.cpp
	src/service/extension/player/delegate.cpp
	src/service/extension/player/tsdelegate.cpp
	src/service/extension/player/player.cpp
	src/service/extension/player/esplayer.cpp
	src/service/extension/player/caption/viewer.cpp
	src/service/extension/player/caption/delegate.cpp
	src/service/ca/types.h
	src/service/ca/conditional.h
	src/service/ca/conditional.cpp
	src/service/ca/system.h
	src/service/ca/system.cpp
	src/service/ca/delegate.h
	src/service/ca/delegate.cpp
	src/service/ca/decrypter.h
	src/service/ca/decrypter.cpp
	src/service/ca/filterdelegateimpl.h
	src/service/ca/filterdelegateimpl.cpp
	src/service/ca/impl/dummy.h
	src/service/ca/impl/dummy.cpp
	src/service/servicemanager.cpp
	src/service/service.cpp
	src/service/serviceid.cpp
	src/service/serviceprovider.cpp
	src/muxer/ts/muxer.cpp
	src/muxer/ts/out/output.cpp
	src/muxer/ts/out/rtp.cpp
	src/muxer/ts/out/file.cpp
	src/demuxer/text.cpp
	src/demuxer/ts/demuxer.cpp
	src/demuxer/ts/demuxerimpl.cpp
	src/demuxer/ts/filter.cpp
	src/demuxer/ts/psiwrapper.h
	src/demuxer/ts/psiwrapper.cpp
	src/demuxer/descriptors.cpp
	src/demuxer/descriptors/generic.cpp
	src/demuxer/descriptors/demuxers.cpp
	src/demuxer/descriptors/ca.cpp
	src/demuxer/descriptors/lcn.cpp
	src/demuxer/descriptors/parental.cpp
	src/demuxer/psi/tableinfo.cpp
	src/demuxer/psi/cache.h
	src/demuxer/psi/cache.cpp
	src/demuxer/psi/psidemuxer.cpp
	src/demuxer/psi/psifilter.cpp
	src/demuxer/psi/pat.cpp
	src/demuxer/psi/patdemuxer.cpp
	src/demuxer/psi/cat.cpp
	src/demuxer/psi/catdemuxer.cpp
	src/demuxer/psi/nit.cpp
	src/demuxer/psi/pmt.cpp
	src/demuxer/psi/cdt.cpp
	src/demuxer/psi/cdtdemuxer.cpp
	src/demuxer/psi/download/sdttdemuxer.cpp
	src/demuxer/psi/download/sdtt.cpp
	src/demuxer/psi/raw.cpp
	src/demuxer/psi/rawdemuxer.cpp
	src/demuxer/psi/ecmdemuxer.cpp
	src/demuxer/psi/sdt.cpp
	src/demuxer/psi/sdtdemuxer.cpp
	src/demuxer/psi/nitdemuxer.cpp
	src/demuxer/psi/pmtdemuxer.cpp
	src/demuxer/psi/eitdemuxer.cpp
	src/demuxer/psi/eit.cpp
	src/demuxer/psi/mjd.cpp
	src/demuxer/psi/tot.cpp
	src/demuxer/psi/totdemuxer.cpp
	src/demuxer/psi/dsmcc/dsmccfilter.cpp
	src/demuxer/psi/dsmcc/datacarouselhelper.cpp
	src/demuxer/psi/dsmcc/objectcarouselfilter.cpp
	src/demuxer/psi/dsmcc/downloadfilter.cpp
	src/demuxer/psi/dsmcc/streameventdemuxer.cpp
	src/demuxer/psi/dsmcc/dsmccdemuxer.cpp
	src/demuxer/psi/dsmcc/dii.cpp
	src/demuxer/psi/dsmcc/dsi.cpp
	src/demuxer/psi/dsmcc/dsmcc.cpp
	src/demuxer/psi/dsmcc/module.cpp
	src/demuxer/psi/dsmcc/event.cpp
	src/demuxer/psi/dsmcc/module/memorydata.cpp
	src/demuxer/psi/dsmcc/module/resourcepool.cpp
	src/demuxer/psi/dsmcc/module/filedata.cpp
	src/demuxer/psi/dsmcc/biop/directory.cpp
	src/demuxer/psi/dsmcc/biop/objectlocation.cpp
	src/demuxer/psi/dsmcc/biop/streamevent.cpp
	src/demuxer/psi/dsmcc/biop/file.cpp
	src/demuxer/psi/dsmcc/biop/biop.cpp
	src/demuxer/psi/dsmcc/biop/object.cpp
	src/demuxer/psi/dsmcc/biop/ior.cpp
	src/demuxer/psi/application/aitdemuxer.cpp
	src/demuxer/psi/application/ait.cpp
	src/demuxer/psi/application/types.cpp
	src/demuxer/pes/pesdemuxer.cpp
	src/demuxer/pes/caption/captiondemuxer.cpp
	src/demuxer/pes/caption/captiondata.cpp
	src/provider/ts/data/frontend.cpp
	src/provider/ts/data/filefrontend.cpp
	src/provider/ts/data/urlfrontend.h
	src/provider/ts/data/urlfrontend.cpp
	src/provider/ts/data/networkfrontend.cpp
	src/provider/ts/filter.cpp
	src/provider/ts/provider.cpp
	src/provider/frontend.cpp
	src/provider/broadcast/frontend.cpp
	src/provider/broadcast/config.cpp
	src/provider/broadcast/isdbtconfig.cpp
	src/provider/broadcast/satelliteconfig.cpp
	src/provider/timer.h
	src/provider/timer.cpp
	src/provider/provider.cpp
	src/provider/filter.cpp
	src/stream/dummy/pipe.cpp
	src/stream/basicpipe.cpp
)

