#!/bin/bash

TAC_ROOT=$DEPOT/tool/tac
TAC_PKGS_ROOT=${TAC_ROOT}/packages
TAC_PKGS_NODE=${TAC_PKGS_ROOT}/node

TAC_MODULES=${TAC_PKGS_ROOT}/node_modules
TAC_COMMON_MODULES=${TAC_PKGS_NODE}/node_modules
TAC_COMMON_MODULES_DEV=${TAC_PKGS_NODE}/node_modules_dev

MOCHA_BIN=${TAC_COMMON_MODULES_DEV}/mocha/bin
JSHINT_BIN=${TAC_COMMON_MODULES_DEV}/jshint/bin

export NODE_PATH=${TAC_MODULES}:${TAC_COMMON_MODULES}:${TAC_COMMON_MODULES_DEV}
export PATH=${PATH}:${MOCHA_BIN}:${JSHINT_BIN}
